<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../MinimalApi.Application/MinimalApi.Application.csproj" />
    <ProjectReference Include="../MinimalApi.Domain/MinimalApi.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>
</Project>
